---
kind: pipeline
name: docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/chamburr/twilight-dispatch
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - push
    - tag
  branch:
    - main
