when:
  - event: tag
  - event: push
    branch: main

steps:
  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/chamburr/twilight-dispatch
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
